/**
* @author Addepar
* @date 2022
* @group Tests
* @description // TO DO: Describe this class
* 
*          SFKB: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing.htm 
*/
@isTest
private class <%= apiName %> {

    @TestSetup
    static void setupTestData(){
        // TO DO
    }

    @isTest
    static void myUnitTest() {
        // TO DO: ARRANGE

        Test.startTest();
        // TO DO: EXECUTE
        Test.stopTest();

        // TO DO: ASSERT
    }
}