/**
* @author Addepar
* @date <Month> <DD>,<YYYY>
* @group //TO DO: assign group
* @description //TO DO: describe this class
*
*               SFKB: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_scheduler.htm
*/
global class <%= apiName %> implements Schedulable {
	/**
	 * @description // TO DO
	 * @param context contains the CronTrigger job Id
	 */ 
   	public void execute(SchedulableContext context) {
		// TO DO
	}
}