/**
* @author Addepar
* @date 2022
* @group // TO DO: Assign group
* @description // TO DO: Describe this class
* 
*          SFKB: https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/controllers_server_apex_pass_data.htm
*/
public with sharing class <%= apiName %> {
    
    @AuraEnabled
    public static void methodName() {
        try{
            // TO DO
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }
}
